// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csfnewhtufuoevcyurtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzZm5ld2h0dWZ1b2V2Y3l1cnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Nzc1MzcsImV4cCI6MjA2NzQ1MzUzN30.eqwOnHZ8TcC08gS4VbNS38aG-J4mHJmpKT0NO8VSHL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});